/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.lang.reflect.Array;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test  void rollTest() {
        int number = 4 ;
        int arr[] = App.roll(number);
        int arr1[]={};
        assertEquals(number, App.roll(number).length);
    }
    @Test void duplicateTest(){
        int arr [] = {1, 2, 3, 4, 5, 5};
        assertEquals(true, App.containsDuplicates(arr));
    }
    @Test void averageTest(){
        int [] arr = {1, 2, 3, 4, 5};
        assertEquals(3.0, App.calculateAverage(arr));
    }
    @Test void arrayAverage(){
        int [][] arr = {{2, 2, 2},{3, 3, 3}, {4, 4, 4},};
        assertEquals(2.0, App.arrayAverage(arr));
    }
}
