/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;


import java.util.ArrayList;

public class Library {


    public static void main(String[] args) {
//        Restaurant Mac = new Restaurant("MACDONALD", 6, "6000");
//        Review review = new Review("the food is good", "Mohammad",2);
//        Mac.addReview(review);
//        System.out.println(Mac);
//        Restaurant Kfc = new Restaurant("KFC" , 4, "7000");
//        Review review1 = new Review("the food is delisious", "Ali", 3);
//        Kfc.addReview(review1);
//        System.out.println(Kfc.toString());

        // Restaurant instance
//        Restaurant restaurant = new Restaurant("Mac", 5, "900");
//        System.out.println(restaurant);
//        Review review2 = new Review("good" , "Ali", 2);
//        restaurant.addReview(review2);
//        System.out.println(restaurant);

        //Shop instance
//        Shop shop = new Shop("Mall", "so beutiful", "$$$");
//        System.out.println(shop.toString());
//        Review shopReview = new Review("its not so good", "Mohammad", 9);
//        shop.addReview(shopReview);
//        System.out.println(shop);

        //Theater instance
        ArrayList <String> movieName = new ArrayList<>();
        movieName.add("Spider Man");
        movieName.add("Taken");
        movieName.add("John wik");
        Theater theater = new Theater(movieName);
        Review theaterReview = new Review("so Goood", "Mahmoud", 7);
        theater.addReview(theaterReview, "Taken");

        System.out.println(theater.toString());
    }
}
