/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {

        ReadFile readFile1 = new ReadFile();
        readFile1.readFile();
        System.out.println("Hello");
    }
}
