/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import Rest.Restaurant;
import Rest.Review;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test void RestaurantTest (){
        Restaurant restaurant = new Restaurant("Macdonaldz", 5, "500$");
        assertEquals("Macdonaldz", restaurant.getName());
    }

    @Test void ReviewTest () {
        Review review = new Review("good", "Mohammad", 4);
        assertEquals("Mohammad", review.getAuthor());
    }

    @Test void addReview () {
        Restaurant restaurant = new Restaurant("Mac", 5, "900");
        Review review = new Review("good" , "Ali", 2);
        restaurant.addReview(review);
        assertEquals(2, restaurant.getNumOfStarsAfterReview());
    }

    @Test void toStringReview () {
        Review review = new Review("good" , "Ali", 2);
        assertEquals("Review{body='good', author='Ali', num_of_stars=2}", review.toString());
    }



}
