/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void Test_method1() {
            int num = 2;
            String name = "cat";
            assertEquals("cat", App.pluralize(name, num));
    }
}
